dictionary APEConstructor
{
    cstring ip;
    unsigned short port = 6969;
};

[
    Constructor(APEConstructor opt),
    exposedName=APE
] interface NativeAPE
{
    attribute EventHandler onclient;
};

