/*dictionary APEConstructor
{
    cstring ip = "0.0.0.0";
    unsigned short port = 6969;
};*/

[
    Constructor(APEConstructor opt),
    className=APE
] interface NativeAPE
{
    attribute EventHandler onclient;
    boolean foobar(int x, cstring foo);
    boolean foobar(int x, cstring foo, int y);
};


